# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScoutMaster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ScoutMaster

	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Storage'

  target 'ScoutMasterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScoutMasterUITests' do
    # Pods for testing
  end

end
